### PR TITLE
Fix `recipe-maintainers`

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/conda-forge.github.io/issues/86

Had a minor syntax error. This removes it. Was causing this [error](https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/122659832#L242).

### CODE REVIEW

**Comment by jakirkham** [comment]
@ocefpaf or @pelson, could one of you please merge this when you have a chance? Thanks.

**Comment by jakirkham** [comment]
@pelson, if there are no issues with this, could you please merge this. The feedstock is currently orphaned as the maintainer was not added. This should fix that.

**Comment by pelson** [comment]
Thanks @jakirkham - yes, this is good. I got carried away with fixing it in conda-smithy and then having some 🍞 breakfast. 😄

**Comment by jakirkham** [comment]
No worries. I know I post so much stuff that I just wanted to make sure this didn't get buried. :wink:

**Comment by pelson** [comment]
Good - keep pining me on the important stuff. If you don't get a response to something you need a response for, you are welcome to use any channel you like to get my attention (unless I'm on vacation 🐚 🍹 🌊 🐳 )

**Pull request merged**
